global:
  scrape_interval: 15s
  external_labels:
    monitor: 'golang-example-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'local'

  - job_name: 'example'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.192.145:9000']
        labels:
          group: 'example'