// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcapi.proto

package grpcapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	raftpb "go.etcd.io/etcd/raft/raftpb"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinRaftResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Nodes                []*NodeInfo `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JoinRaftResponse) Reset()         { *m = JoinRaftResponse{} }
func (m *JoinRaftResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRaftResponse) ProtoMessage()    {}
func (*JoinRaftResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{0}
}

func (m *JoinRaftResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRaftResponse.Unmarshal(m, b)
}
func (m *JoinRaftResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRaftResponse.Marshal(b, m, deterministic)
}
func (m *JoinRaftResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRaftResponse.Merge(m, src)
}
func (m *JoinRaftResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRaftResponse.Size(m)
}
func (m *JoinRaftResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRaftResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRaftResponse proto.InternalMessageInfo

func (m *JoinRaftResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *JoinRaftResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *JoinRaftResponse) GetNodes() []*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type LeaveRaftResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRaftResponse) Reset()         { *m = LeaveRaftResponse{} }
func (m *LeaveRaftResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveRaftResponse) ProtoMessage()    {}
func (*LeaveRaftResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{1}
}

func (m *LeaveRaftResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRaftResponse.Unmarshal(m, b)
}
func (m *LeaveRaftResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRaftResponse.Marshal(b, m, deterministic)
}
func (m *LeaveRaftResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRaftResponse.Merge(m, src)
}
func (m *LeaveRaftResponse) XXX_Size() int {
	return xxx_messageInfo_LeaveRaftResponse.Size(m)
}
func (m *LeaveRaftResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRaftResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRaftResponse proto.InternalMessageInfo

func (m *LeaveRaftResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LeaveRaftResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SendResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{2}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type PutObjectRequest struct {
	Object               *Pair    `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectRequest) Reset()         { *m = PutObjectRequest{} }
func (m *PutObjectRequest) String() string { return proto.CompactTextString(m) }
func (*PutObjectRequest) ProtoMessage()    {}
func (*PutObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{3}
}

func (m *PutObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectRequest.Unmarshal(m, b)
}
func (m *PutObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectRequest.Marshal(b, m, deterministic)
}
func (m *PutObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectRequest.Merge(m, src)
}
func (m *PutObjectRequest) XXX_Size() int {
	return xxx_messageInfo_PutObjectRequest.Size(m)
}
func (m *PutObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectRequest proto.InternalMessageInfo

func (m *PutObjectRequest) GetObject() *Pair {
	if m != nil {
		return m.Object
	}
	return nil
}

type PutObjectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectResponse) Reset()         { *m = PutObjectResponse{} }
func (m *PutObjectResponse) String() string { return proto.CompactTextString(m) }
func (*PutObjectResponse) ProtoMessage()    {}
func (*PutObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{4}
}

func (m *PutObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectResponse.Unmarshal(m, b)
}
func (m *PutObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectResponse.Marshal(b, m, deterministic)
}
func (m *PutObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectResponse.Merge(m, src)
}
func (m *PutObjectResponse) XXX_Size() int {
	return xxx_messageInfo_PutObjectResponse.Size(m)
}
func (m *PutObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectResponse proto.InternalMessageInfo

func (m *PutObjectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PutObjectResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ListObjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListObjectsRequest) Reset()         { *m = ListObjectsRequest{} }
func (m *ListObjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListObjectsRequest) ProtoMessage()    {}
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{5}
}

func (m *ListObjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectsRequest.Unmarshal(m, b)
}
func (m *ListObjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListObjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectsRequest.Merge(m, src)
}
func (m *ListObjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListObjectsRequest.Size(m)
}
func (m *ListObjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectsRequest proto.InternalMessageInfo

type ListObjectsResponse struct {
	Objects              []*Pair  `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListObjectsResponse) Reset()         { *m = ListObjectsResponse{} }
func (m *ListObjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListObjectsResponse) ProtoMessage()    {}
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{6}
}

func (m *ListObjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectsResponse.Unmarshal(m, b)
}
func (m *ListObjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectsResponse.Marshal(b, m, deterministic)
}
func (m *ListObjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectsResponse.Merge(m, src)
}
func (m *ListObjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListObjectsResponse.Size(m)
}
func (m *ListObjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectsResponse proto.InternalMessageInfo

func (m *ListObjectsResponse) GetObjects() []*Pair {
	if m != nil {
		return m.Objects
	}
	return nil
}

type ListMembersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMembersRequest) Reset()         { *m = ListMembersRequest{} }
func (m *ListMembersRequest) String() string { return proto.CompactTextString(m) }
func (*ListMembersRequest) ProtoMessage()    {}
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{7}
}

func (m *ListMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersRequest.Unmarshal(m, b)
}
func (m *ListMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersRequest.Marshal(b, m, deterministic)
}
func (m *ListMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersRequest.Merge(m, src)
}
func (m *ListMembersRequest) XXX_Size() int {
	return xxx_messageInfo_ListMembersRequest.Size(m)
}
func (m *ListMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersRequest proto.InternalMessageInfo

type ListMembersResponse struct {
	Members              []*NodeInfo `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListMembersResponse) Reset()         { *m = ListMembersResponse{} }
func (m *ListMembersResponse) String() string { return proto.CompactTextString(m) }
func (*ListMembersResponse) ProtoMessage()    {}
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{8}
}

func (m *ListMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersResponse.Unmarshal(m, b)
}
func (m *ListMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersResponse.Marshal(b, m, deterministic)
}
func (m *ListMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersResponse.Merge(m, src)
}
func (m *ListMembersResponse) XXX_Size() int {
	return xxx_messageInfo_ListMembersResponse.Size(m)
}
func (m *ListMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersResponse proto.InternalMessageInfo

func (m *ListMembersResponse) GetMembers() []*NodeInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

type NodeInfo struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=Addr,proto3" json:"Addr,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=Port,proto3" json:"Port,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{9}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NodeInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NodeInfo) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *NodeInfo) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Pair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7b78476b7b33751, []int{10}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*JoinRaftResponse)(nil), "grpcapi.JoinRaftResponse")
	proto.RegisterType((*LeaveRaftResponse)(nil), "grpcapi.LeaveRaftResponse")
	proto.RegisterType((*SendResponse)(nil), "grpcapi.SendResponse")
	proto.RegisterType((*PutObjectRequest)(nil), "grpcapi.PutObjectRequest")
	proto.RegisterType((*PutObjectResponse)(nil), "grpcapi.PutObjectResponse")
	proto.RegisterType((*ListObjectsRequest)(nil), "grpcapi.ListObjectsRequest")
	proto.RegisterType((*ListObjectsResponse)(nil), "grpcapi.ListObjectsResponse")
	proto.RegisterType((*ListMembersRequest)(nil), "grpcapi.ListMembersRequest")
	proto.RegisterType((*ListMembersResponse)(nil), "grpcapi.ListMembersResponse")
	proto.RegisterType((*NodeInfo)(nil), "grpcapi.NodeInfo")
	proto.RegisterType((*Pair)(nil), "grpcapi.Pair")
}

func init() { proto.RegisterFile("grpcapi.proto", fileDescriptor_a7b78476b7b33751) }

var fileDescriptor_a7b78476b7b33751 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x9d, 0xd8, 0x6d, 0x92, 0x49, 0x0b, 0xe9, 0x10, 0x24, 0x63, 0x38, 0x44, 0x2b, 0x41,
	0x23, 0x21, 0x39, 0x28, 0x9c, 0x40, 0xa8, 0x12, 0x10, 0x0e, 0xa9, 0x5a, 0x88, 0x96, 0x4b, 0xaf,
	0x8e, 0x3d, 0xb1, 0x4c, 0xa9, 0xd7, 0x78, 0x9d, 0x4a, 0xbc, 0x05, 0x8f, 0x8c, 0x76, 0xd7, 0x76,
	0x53, 0x3b, 0xa7, 0xf6, 0x12, 0xcf, 0xfc, 0xeb, 0xf9, 0x67, 0x66, 0xf3, 0x25, 0x70, 0x1c, 0xe7,
	0x59, 0x18, 0x64, 0x89, 0x9f, 0xe5, 0xa2, 0x10, 0xd8, 0x2b, 0x53, 0xef, 0x4d, 0x2c, 0x7c, 0x2a,
	0xc2, 0xc8, 0x4f, 0xc4, 0x4c, 0x3d, 0x67, 0x79, 0xb0, 0x29, 0xf4, 0x47, 0xb6, 0xd6, 0x0f, 0x53,
	0xe0, 0x8d, 0x63, 0x11, 0x0b, 0x1d, 0xce, 0x54, 0x64, 0x54, 0x76, 0x0d, 0xa3, 0x73, 0x91, 0xa4,
	0x3c, 0xd8, 0x14, 0x9c, 0x64, 0x26, 0x52, 0x49, 0xe8, 0x42, 0x4f, 0x6e, 0xc3, 0x90, 0xa4, 0x74,
	0x3b, 0x93, 0xce, 0xb4, 0xcf, 0xab, 0x14, 0xc7, 0x70, 0x40, 0x79, 0x2e, 0x72, 0xb7, 0x3b, 0xe9,
	0x4c, 0x07, 0xdc, 0x24, 0x78, 0x0a, 0x07, 0xa9, 0x88, 0x48, 0xba, 0xf6, 0xc4, 0x9e, 0x0e, 0xe7,
	0x27, 0x7e, 0x35, 0xe9, 0x77, 0x11, 0xd1, 0x32, 0xdd, 0x08, 0x6e, 0xce, 0xd9, 0x57, 0x38, 0xb9,
	0xa0, 0xe0, 0x96, 0x1e, 0xd3, 0x8d, 0x9d, 0xc1, 0xd1, 0x4f, 0x4a, 0xa3, 0x07, 0xd7, 0x7f, 0x80,
	0xd1, 0x6a, 0x5b, 0xfc, 0x58, 0xff, 0xa2, 0xb0, 0xe0, 0xf4, 0x67, 0x4b, 0xb2, 0xc0, 0xd7, 0x70,
	0x28, 0xb4, 0xa0, 0x2d, 0x86, 0xf3, 0xe3, 0x7a, 0x85, 0x55, 0x90, 0xe4, 0xbc, 0x3c, 0x54, 0xf3,
	0xef, 0x94, 0x3e, 0xb0, 0xff, 0x18, 0xf0, 0x22, 0x91, 0xa5, 0x8b, 0x2c, 0x27, 0x60, 0x67, 0xf0,
	0xec, 0x9e, 0x5a, 0x9a, 0x9f, 0x42, 0xcf, 0xf4, 0x56, 0xe6, 0x76, 0x7b, 0xb2, 0xea, 0xb4, 0x72,
	0xbd, 0xa4, 0x9b, 0x35, 0xe5, 0xb5, 0xeb, 0x17, 0xe3, 0x5a, 0xab, 0xa5, 0xeb, 0x5b, 0xe8, 0xdd,
	0x18, 0xa9, 0x74, 0xdd, 0xf3, 0x95, 0x55, 0x6f, 0xb0, 0x2b, 0xe8, 0x57, 0x22, 0x3e, 0x81, 0xee,
	0x72, 0xa1, 0xd7, 0x74, 0x78, 0x77, 0xb9, 0x40, 0x04, 0xe7, 0x73, 0x14, 0x55, 0x0b, 0xea, 0x58,
	0x69, 0x2b, 0x91, 0x17, 0xae, 0x6d, 0x34, 0x15, 0xab, 0x9b, 0xf8, 0xa6, 0x6f, 0xc2, 0x31, 0x37,
	0xa1, 0x13, 0xe6, 0x83, 0xa3, 0x96, 0xc0, 0x11, 0xd8, 0xd7, 0xf4, 0x57, 0xdb, 0x0e, 0xb8, 0x0a,
	0xd5, 0xfb, 0xb7, 0xc1, 0xef, 0x2d, 0x69, 0xe3, 0x23, 0x6e, 0x92, 0xf9, 0x3f, 0x1b, 0x1c, 0x85,
	0x0e, 0x7e, 0x84, 0x7e, 0x05, 0x2d, 0xb6, 0x47, 0xf7, 0x5e, 0xd4, 0x52, 0x13, 0x6d, 0x66, 0xe1,
	0x27, 0x18, 0xd4, 0x0c, 0xee, 0x2b, 0xf6, 0x6a, 0xa9, 0x85, 0x2a, 0xb3, 0xf0, 0x1d, 0x38, 0x0a,
	0x3e, 0x7c, 0xea, 0x9b, 0x1f, 0x98, 0x7f, 0x49, 0x52, 0x06, 0x31, 0x79, 0xcf, 0xeb, 0xb2, 0x5d,
	0x38, 0x99, 0x85, 0x0b, 0x18, 0xd4, 0xcc, 0xe0, 0xdd, 0x64, 0x4d, 0x04, 0x77, 0xfa, 0xb6, 0x10,
	0x63, 0x16, 0x9e, 0xc3, 0x70, 0x07, 0x0f, 0x7c, 0x79, 0x37, 0x64, 0x0b, 0x25, 0xef, 0xd5, 0xfe,
	0xc3, 0xa6, 0x57, 0x09, 0x45, 0xc3, 0xeb, 0x3e, 0x40, 0x0d, 0xaf, 0x06, 0x47, 0xcc, 0xba, 0xea,
	0xac, 0x0f, 0xf5, 0xff, 0xc8, 0xfb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0xb9, 0x95, 0x89,
	0x9f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftClient interface {
	JoinRaft(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*JoinRaftResponse, error)
	LeaveRaft(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*LeaveRaftResponse, error)
	Send(ctx context.Context, in *raftpb.Message, opts ...grpc.CallOption) (*SendResponse, error)
	PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error)
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) JoinRaft(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*JoinRaftResponse, error) {
	out := new(JoinRaftResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.Raft/JoinRaft", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) LeaveRaft(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*LeaveRaftResponse, error) {
	out := new(LeaveRaftResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.Raft/LeaveRaft", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) Send(ctx context.Context, in *raftpb.Message, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.Raft/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error) {
	out := new(PutObjectResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.Raft/PutObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.Raft/ListObjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.Raft/ListMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServer is the server API for Raft service.
type RaftServer interface {
	JoinRaft(context.Context, *NodeInfo) (*JoinRaftResponse, error)
	LeaveRaft(context.Context, *NodeInfo) (*LeaveRaftResponse, error)
	Send(context.Context, *raftpb.Message) (*SendResponse, error)
	PutObject(context.Context, *PutObjectRequest) (*PutObjectResponse, error)
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_JoinRaft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).JoinRaft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Raft/JoinRaft",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).JoinRaft(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_LeaveRaft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).LeaveRaft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Raft/LeaveRaft",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).LeaveRaft(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(raftpb.Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Raft/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).Send(ctx, req.(*raftpb.Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_PutObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).PutObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Raft/PutObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).PutObject(ctx, req.(*PutObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Raft/ListObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Raft/ListMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinRaft",
			Handler:    _Raft_JoinRaft_Handler,
		},
		{
			MethodName: "LeaveRaft",
			Handler:    _Raft_LeaveRaft_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Raft_Send_Handler,
		},
		{
			MethodName: "PutObject",
			Handler:    _Raft_PutObject_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _Raft_ListObjects_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _Raft_ListMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcapi.proto",
}
